### ISSUE TITLE
finsweet CMS Filter not working along with select2

### ISSUE THREAD

**Issue by chaitanya71998** [finsweet/sweetjs#58]
Hi Greetings,

I had a CMS collection list. i added all the steps to make a select filter and it was working fine.
But I wanted a searchable dropdown filter like shown below. so i made the same select dropdown to be a select2, which gives feasibility for searchable dropdown as mentioned in the basic usage of the select2 documentation .
After using this select2, the finsweet filter functionality is not working
**finsweet filter link**: [CMS Filter for Webflow - No-code using Attributes](https://finsweet.com/attributes/cms-filter)
**select2 documentation link**: [Basic usage | Select2 - The jQuery replacement for select boxes](https://select2.org/getting-started/basic-usage)

```
<script async src="https://cdn.jsdelivr.net/npm/@finsweet/attributes-cmsfilter@1/cmsfilter.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
$(document).ready(function() {
    $('#designation').select2();
});

</script>
```
![image](https://user-images.githubusercontent.com/46353549/208063700-88a4d0d5-2199-44c6-a53d-c9348038f548.png)

**Comment by alexiglesias93** [comment]
Hello @chaitanya71998, this issue is related to Attributes, which is a different repository (soon to be public).
If you need to receive support about Attributes, please refer to https://finsweet.com/attributes/support

Bests!

**Comment by chaitanya71998** [comment]
Hi @alexiglesias93 , thanks for your response. After running the checks even i got everything is fine but the things aren't working
 Can you help me in solving this problem? 
![image](https://user-images.githubusercontent.com/46353549/208098181-3dd31328-9084-4472-ae9d-edb7df4393cb.png)

**Comment by alexiglesias93** [comment]
@chaitanya71998 can you share a live URL of your project?

**Comment by chaitanya71998** [comment]
here is the link https://dropdowns-testing.webflow.io/

**Comment by alexiglesias93** [comment]
@chaitanya71998 seems like jQuery's select2 is preventing the `input` events from bubbling, which causes `cmsfilter` to not catch them.
Just update this piece of code from this:
```javascript
        <script>
            $(document).ready(function() {
                var $eventSelect = $("#designation")
                $eventSelect.select2()
                $eventSelect.on("select2:select", function(e) {
                    console.log("select2:select", e);
                })
            })
        </script>
```
To this:
```javascript
        <script>
            $(document).ready(function() {
                var $eventSelect = $("#designation")
                $eventSelect.select2()
                $eventSelect.on("select2:select", function(e) {
                    $eventSelect[0].dispatchEvent(new Event('input', { bubbles: true }));
                })
            })
        </script>
```

**Comment by chaitanya71998** [comment]
thank you @alexiglesias93 , I had updated as described above, its working fine.
